### ISSUE TITLE
Clarification on runtime loading of strings

### ISSUE THREAD

**Issue by SirWindfield** [bheisler/TinyTemplate#12]
Hey!

The documentation mentions the following:

> Although it is possible to use TinyTemplate with template strings loaded at runtime, this is not recommended.

What is the reason behind this? I am currently looking for a fast and rather lightweight templating engine that allows branching as well and after tinkering around with this crate, it seems to work perfectly.

**Comment by bheisler** [comment]
I think it's mostly because managing the lifetimes of the template strings would be a hassle. TinyTemplate borrows the template strings, so the TinyTemplate object can't outlive any of the templates. That's easy when the templates are static string literals, but harder when they're loaded at runtime.

It should work just fine either way, it's just that that's not the use case TinyTemplate is designed for.

**Comment by SirWindfield** [comment]
Thanks for clarifying!
