### ISSUE TITLE
Loop over root element

### ISSUE THREAD

**Issue by CodeSandwich** [bheisler/TinyTemplate#3]
I have a vector of structures, which I want to format. Unfortunately I can't access the root element to loop over it: `{{ for item in ??? }} {item.field} {{ endfor }}`. Is it possible? What template should I write?

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

Y'know, it never occurred to me that anyone would want that (I'm still kind of surprised when I find out anyone but Criterion.rs is using TinyTemplate). I don't think that's possible right now, except to wrap your vector in its own struct so that you can give it a name.

Thing is, I'm not really sure if I want to support this. The obvious way to support it is to add a special `@root` keyword, but since the workaround is easy, it's not obvious that it's worth the tradeoff. I'll have to think about that.

**Comment by CodeSandwich** [comment]
Don't be surprised, TinyTemplate is a great tool for formatting complex data!

The `@root` would be perfect. Another solution would be to allow paths to start from a `.` to explicitly indicate that they are absolute. That was one of the first things I felt was right to try: `{{ for item in . }} ...`.

That's a pity, but I will understand. The wrapper is exactly what I ended up doing, but it's an ugly workaround.

**Comment by luciusmagn** [comment]
Would be cool to support that! tinytemplate is otherwise really great!

**Comment by bheisler** [comment]
Alright, seems this is more desired than I thought. It wasn't too hard to add support for. I've added the `@root` keyword in 1.0.4; if the root context value is the right type you can print it, branch on it, or iterate over it.
